# Generated by Django 5.0.6 on 2024-08-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_category_product_category'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(related_name='products_tags', to='tags.tag', verbose_name='Теги'),
        ),
    ]
