# Generated by Django 5.0.6 on 2024-08-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('products', '0009_product_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comment',
        ),
        migrations.AddField(
            model_name='product',
            name='comment',
            field=models.ManyToManyField(related_name='products_comment', to='comments.comment', verbose_name='Коментарии'),
        ),
    ]
