# Generated by Django 5.0.6 on 2024-08-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_quantity_cartitem_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='added',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
