# Generated by Django 5.0.6 on 2024-08-10 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_order_options_remove_order_user_orderpage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_order', to='cart.orderpage', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='orderpage',
            name='created',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
