# Generated by Django 5.0.6 on 2024-08-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_order_order_page_alter_orderpage_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpage',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
