# Generated by Django 5.0.6 on 2024-08-10 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_orderpage_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created',
        ),
        migrations.RemoveField(
            model_name='orderpage',
            name='created',
        ),
    ]
