# Generated by Django 5.0.6 on 2024-08-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_remove_cart_created_remove_orderpage_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_page',
            new_name='order',
        ),
    ]
