# Generated by Django 5.0.6 on 2024-08-06 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_parent'),
        ('likes', '0003_like_is_liked_alter_like_comment_alter_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_comment', to='comments.comment'),
        ),
    ]
