# Generated by Django 5.0.6 on 2024-08-08 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0005_rename_created_at_like_added_and_more'),
        ('products', '0012_alter_product_image1_alter_product_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_product', to='products.product'),
        ),
    ]
