# Generated by Django 5.0.6 on 2024-08-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
    ]
