# Generated by Django 5.0.6 on 2024-08-08 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
